#/config/membersInfo.do=membersinfo.command.membersinfoHandler
/config/membersInfo.do=membersinfo.command.ReadMembersInfoHandler
/config/updateMembersInfo.do=membersinfo.command.UpdateMembersInfoHandler
