/Config/employeeIns1.do=config.employee.command.EmployeeRegister1Handler
/Config/employeeIns2.do=config.employee.command.EmployeeRegister2Handler
/Config/payitemsetlist.do=config.payitemset.command.PayItemSetListHandler
/Config/payitemsetselect.do=config.payitemset.command.PayItemSetSelectHandler
/Config/payitemsetinsert.do=config.payitemset.command.PayItemSetInsertHandler
/Config/payitemsetupdate.do=config.payitemset.command.PayItemSetUpdateHandler
/Config/payitemsetdelete.do=config.payitemset.command.PayItemSetDeleteHandler
/Config/payitemsetclear.do=config.payitemset.command.PayItemSetClearHandler
/Config/nontaxdetailpopup.do=config.payitemset.command.NonTaxDetailPopupHandler
/Config/deductionitemsetlist.do=config.payitemset.command.DeductionItemSetListHandler
/Config/deductionitemsetselect.do=config.payitemset.command.DeductionItemSetSelectHandler
/Config/deductionitemsetinsert.do=config.payitemset.command.DeductionItemSetInsertHandler
/Config/deductionitemsetupdate.do=config.payitemset.command.DeductionItemSetUpdateHandler
/Config/deductionitemsetdelete.do=config.payitemset.command.DeductionItemSetDeleteHandler
/Config/deductionitemsetclear.do=config.payitemset.command.DeductionItemSetClearHandler
/config/membersInfo.do=config.membersinfo.command.ReadMembersInfoHandler
/config/updateMembersInfo.do=config.membersinfo.command.UpdateMembersInfoHandler
/Config/leavesettingslist.do=config.dnLItemSet.command.LeaveSettingsListHandler
/Config/leavetypeselect.do=config.dnLItemSet.command.LeaveTypeSelectHandler
/Config/leavetypeinsert.do=config.dnLItemSet.command.LeaveTypeInsertHandler
/Config/leavetypeupdate.do=config.dnLItemSet.command.LeaveTypeUpdateHandler
/Config/leavetypedelete.do=config.dnLItemSet.command.LeaveTypeDeleteHandler
/Config/attendancetypeselect.do=config.dnLItemSet.command.AttendanceTypeSelectHandler
/Config/attendancetypeinsert.do=config.dnLItemSet.command.AttendanceTypeInsertHandler
/Config/attendancetypeupdate.do=config.dnLItemSet.command.AttendanceTypeUpdateHandler
/Config/attendancetypedelete.do=config.dnLItemSet.command.AttendanceTypeDeleteHandler
/Config/employeeleavemanage.do=config.dnLItemSet.command.EmployeeLeaveManageHandler
/Config/employeeleavesave.do=config.dnLItemSet.command.EmployeeLeaveSaveHandler
/Config/employeeleavedelete.do=config.dnLItemSet.command.EmployeeLeaveDeleteHandler
/Config/employeeleaveautocalc.do=config.dnLItemSet.command.EmployeeLeaveAutoCalcHandler
/Config/membersInfo.do=config.membersinfo.command.ReadMembersInfoHandler
/Config/updateMembersInfo.do=config.membersinfo.command.UpdateMembersInfoHandler
/Person/employeeMnt.do=person.employeeMnt.command.EmployeeMntReadHandler
/Person/employeeMntDelete.do=person.employeeMnt.command.EmployeeMntDeleteHandler
/Person/employeeCard.do=person.employeeCard.command.EmployeeCardReadHandler
/Payment/paymenttransfer.do=payment.paymenttransfer.command.PaymenttransferHandler
/Payment/paymenttransferlist.do=payment.paymenttransferlist.command.PaymenttransferlistHandler
/Payment/paymentPayItemPart.do=payment.paymentpayitempart.command.PaymentpayitempartHandler
/Payment/fourinsureList.do=payment.fourinsureList.command.FourinsureListHandler
/Person/certificatePrintWorking.do=person.certificatePrintWorking.command.CertificatePrintWorkingReadHandler
/Person/certificatePrintWorkingInsert.do=person.certificatePrintWorking.command.CertificatePrintWorkingInsertHandler
/Person/certificateRegister.do=person.certificateRegister.command.CertificateRegisterReadHandler
/Person/certificateRegisterUpdate.do=person.certificateRegister.command.CertificateRegisterUpdateHandler
/Payment/paymentMnt.do=payment.paymentMnt.controller.PaymentMntController
/Payment/employeeAddModal.do=payment.paymentMnt.command.EmployeeAddModalHandler
/Payment/paymentEmployeeInsert.do=payment.paymentMnt.command.PaymentEmployeeInsertHandler
/Payment/detailAjax.do=payment.paymentMnt.command.PaymentMntDetailAjaxHandler
/Payment/save.do=payment.paymentMnt.command.PaymentMntSaveHandler
/Payment/loadPrevAjax.do=payment.paymentMnt.command.PaymentMntLoadPrevAjaxHandler
/Diligence/diligenceMnt.do=diligence.attendancemanage.command.DiligenceMntHandler
/Diligence/diligenceMntSelect.do=diligence.attendancemanage.command.DiligenceMntSelectHandler
/Diligence/diligenceMntInsert.do=diligence.attendancemanage.command.DiligenceMntInsertHandler
/Diligence/diligenceMntDelete.do=diligence.attendancemanage.command.DiligenceMntDeleteHandler
/Diligence/diligenceMntLeaveStatus.do=diligence.attendancemanage.command.DiligenceMntLeaveStatusHandler
/Diligence/diligenceMntUpdate.do=diligence.attendancemanage.command.DiligenceMntUpdateHandler
/Diligence/diligenceSearchMonth.do=diligence.searchmonth.command.DiligenceSearchMonthHandler
/Payment/paymentMntDayWorker.do=payment.paymentMntDayWorker.controller.PaymentMntDayWorkerController
/Payment/dayWorkerEmployeeAddModal.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerEmployeeAddModalHandler
/Payment/dayWorkerEmployeeInsert.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerEmployeeInsertHandler
/Payment/dayWorkerDetailAjax.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerDetailAjaxHandler
/Payment/dayWorkerSave.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerSaveHandler
/Payment/dayWorkerDeleteSelected.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerDeleteSelectedHandler
/Payment/dayWorkerDeleteAll.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerDeleteAllHandler
/Payment/dayWorkerSummaryAjax.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerSummaryAjaxHandler
/Statistics/paymentStatisticsAll.do=statistics.paymentstatisticsall.command.PaymentStatisticsAllHandler
/Statistics/paymentStatisticsAllMonth.do=statistics.paymentstatisticsallmonth.command.PaymentStatisticsAllMonthHandler
/Payment/dayWorkerSummaryAjax.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerSummaryAjaxHandler
/Retire/retireProcess.do=retirement.retireProcess.command.RetirementProcessReadHandler
/Retire/retireProcessUpdate.do=retirement.retireProcess.command.RetirementProcessUpdateHandler
/Statistics/paymentStatisticsPayItems.do=statistics.paymentstatisticspayitems.command.PaymentStatisticsPayItemsHandler
/Statistics/paymentStatisticsPayItemsEmployeePopup.do=statistics.paymentstatisticspayitems.command.PaymentStatisticsPayItemsEmployeePopupHandler
/Payment/dayWorkerSummaryAjax.do=payment.paymentMntDayWorker.command.PaymentMntDayWorkerSummaryAjaxHandler
