/Payment/paymentMnt.do = payment.paymentMnt.controller.PaymentMntController
/Payment/employeeAddModal.do=payment.paymentMnt.command.EmployeeAddModalHandler
/Payment/insertPayrollEmployee.do=payment.paymentMnt.command.PaymentEmployeeInsertHandler